### ISSUE TITLE
从设置页面返回时会出现NullPointerException

### ISSUE THREAD

**Issue by czvn** [a1018875550/Gank.io#1]
在三星G900F机器上测试出现该问题。
该机器在从MainActivity跳转到SettingActivity后会将MainActivity销毁掉，并触发onSaveInstanceState方法。此时按返回键回到主界面，GankioFragment会重新执行onCreateView，并由于type为空，导致空指针异常应用Crash。
需要在GankioFragment的onSaveInstanceState将type保存。

**Comment by a1018875550** [comment]
好的，非常感谢；
