### ISSUE TITLE
有个问题想问一下作者

### ISSUE THREAD

**Issue by WangChangQin** [a1018875550/Gank.io#4]
在任意代码PresenterImpl中,P层持有V和M的引用。
` 
 private DailyGankModel mDailyGankModel;
    private DailyGankView mDailyGankView;
@Inject
    public DailyGankPresenterImpl(DailyGankModel dailyGankModel, DailyGankView dailyGankView) {
        mDailyGankModel = dailyGankModel;
        mDailyGankView = dailyGankView;
        formatter = new SimpleDateFormat("yyyy-MM-dd");
    }`

这个dagger2会自动寻找实现了该接口的类去实例化吗？为什么我仿照写就老是报错呢？

**Comment by WangChangQin** [comment]
我找到了，是di那还注册了presenter,view,model的。这样会不会太繁琐了啊，有没有什么简便方法呢

**Comment by a1018875550** [comment]
额，我这个是dagger2基础的写法，你可以去研究下dagger2
